### PR TITLE
Fix plugin install s3_sns_sqs -> s3-sns-sqs

### PR DESCRIPTION
**Pull request by christianherweg0807**
Hi everybody.
As mentiont in Bug https://github.com/cherweg/logstash-input-s3-sns-sqs/issues/36 there is an typo in this documentation.

Plz merge...

regards
christian

### CODE REVIEW

**Comment by christianherweg0807** [comment]
I´ve signed the CLA now. :-)

**Comment by karenzone** [comment]
jenkins test this please

**Comment by JoshMock** [comment]
cla/check

**Comment by karenzone** [comment]
Hi @christianherweg0807 
In our CLA checker, the URL to your github page is showing up as `https://github.com/%20christianherweg0807` rather than `https://github.com/christianherweg0807`.  It looks like an extra space might have been introduced when you signed.  Will you take a look, please? 

We're also failing the docs build because the `s3_sns_sqs` value matches our naming standards and is being used in other places. I will give some thought to the best way to resolve the mismatch between our docs and the name of your repo, and get back with you.

**Pull request merged**
