### PR TITLE
Catch missed es-output changes.

### PR DESCRIPTION
**Pull request by mashhurs**
### Description
We generated and added `logstash-integration-logstash` plugin placeholder to the repo. After that, when we generated VPR we witnessed that workflow couldn't catch es-output changes. The reason behind, when we generated VPR, we get the last commit date (`git log -1 --date=short --pretty=format:%cd`) and seek the new published gems after that date.

### Solution
I will create an issue and discuss expected behaviour with a team but this PR is a temporary unblock the doc process.

### CODE REVIEW

**Review by karenzone — APPROVED** [review]
LGTM!  This is the one I was looking for.  Did we miss any others that need to be added back?

**Comment by karenzone** [comment]
> Another interesting point (I don't think it is related with placeholder), logstash-integration-kafka plugin is reverse, I mean in LR, its version is v11.3.0 but VPR v11.3.1. Maybe we didn't update the reference docs?

I can take a look. The LSR is probably OK.  Unlike the VPR, it tends to behave itself ( :-) ). Also:
* The gemlock file controls which plugin versions are allowed in for stack releases. 
* Plugins for the LSR are manually generated by branch for releases.

**Comment by karenzone** [comment]
The last commit to add useragent and protobuf broke docs-ci.  :-(   I don't have time to look right now, so lets consider backing out the last commit, and merging the es-output v11.18.0 that I need for a special project. 

In the meantime, I'm changing my review to blocked.  If this PR gets merged as is, it will bring down our entire elastic.co docs build.

**Review by karenzone — CHANGES_REQUESTED** [review]
Last commit is causing docs-ci to fail, and I can't look at it right now.

**Comment by mashhurs** [comment]
> Last commit is causing docs-ci to fail, and I can't look at it right now.

🤦 useragent has multiple versions and one of them wasn't included. Now CI is 🟢

**Comment by karenzone** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by karenzone** [comment]
@mashhurs 
>@mashhurs, thanks for the most recent fix. It looks good.
Here's an update and flight plan:

>You said that we need to be sure that no plugins doc updates are "in escrow" before we merge a manual fix, such as this one. I've generated https://github.com/elastic/logstash-docs/pull/1557, and will review and merge it shortly.
Then I'll LGTM this PR and ping you so we can merge this one.
I believe that'll get us back on track.

UPDATE:
I'm re-running docs-ci on this PR. It should pass, and then you'll get LGTM.

**Review by karenzone — APPROVED** [review]
LGTM!  As you suggested, I generated and merged #1557 to avoid getting out of sync again.

**Comment by karenzone** [comment]
47482

**Pull request merged**
