### PR TITLE
Include input-s3_sns_sqs plugin landing page

### PR DESCRIPTION
**Pull request by karenzone**
Adds input-s3_sns_sqs plugin landing page with pointers to external repo and docs, and removes the "Edit Me" link.

### CODE REVIEW

**Comment by karenzone** [comment]
Preview: http://logstash-docs_814.docs-preview.app.elstc.co/guide/en/logstash/master/input-plugins.html

**Comment by christianherweg0807** [comment]
Thank you. This looks good to me!

**Comment by ckauf** [comment]
Thanks for confirming @christianherweg0807

We are good to go @karenzone

**Comment by karenzone** [comment]
Thanks for contributing this plugin, @christianherweg0807!

**Pull request closed without merging**
