### PR TITLE
update plugins for 6.4

### PR DESCRIPTION
**Pull request by karenzone**
Manually generated plugin update for 6.4.
Reason: Generate google_pubsub doc so it can be added to Logstash Reference Guide

This is my first time generating the plugin updates, and may be my last now that we have the new automated build process.  Keep me honest!

### CODE REVIEW

**Comment by karenzone** [comment]
@dedemorton  I did local builds of everything with no errors.  That doesn't account for old content reappearing.

**Comment by dedemorton** [comment]
@karenzone Right, that makes sense because these's topics probably aren't in the overview files, so they aren't getting built.

**Comment by jsvd** [comment]
It seems the [skip list](https://github.com/elastic/docs-tools/blob/master/settings.yml) hasn't been updated correctly, it is missing:

```
  - logstash-codec-s3plain
  - logstash-filter-anonymize
  - logstash-filter-unique
  - logstash-filter-multiline
```

It could be that folks who have been generated docs edited the skip list locally only (/me is guilty)
@karenzone could you open a PR against docs-tools adding these?

**Comment by karenzone** [comment]
Yes!  I'll open the PR.  Thanks, @dede and @jsvd. I appreciate your help

**Comment by jsvd** [comment]
https://github.com/elastic/docs-tools/pull/23 has been merged so we can regenerate/update these PRs

**Comment by karenzone** [comment]
Closed without merging due to issues with the skiplist. 
Replaced by #614

**Pull request closed without merging**
