### PR TITLE
updated docs for master

### PR DESCRIPTION
**Pull request by logstashmachine**

### CODE REVIEW

**Comment by jsvd** [comment]
@karenzone doc builds on master are back online: https://logstash-ci.elastic.co/view/Docs/job/elastic+docs-tools+logstash-plugin-docs/168/console. Failing on ES filter atm:
```
15:15:15 INFO:build_docs:Bad cross-document links:
15:15:15 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/logstash/master/plugins-filters-elasticsearch.html contains broken links to:
15:15:15 INFO:build_docs:   - en/logstash/current/connecting-to-cloud.html#_cloud_auth
15:15:15 INFO:build_docs:   - en/logstash/current/connecting-to-cloud.html#_cloud_id
15:15:15 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/logstash/master/plugins-inputs-log4j.html contains broken links to:
15:15:15 INFO:build_docs:   - en/beats/filebeat/current/filebeat-configuration.html
15:15:15 INFO:build_docs:   - en/beats/filebeat/current/filebeat-installation.html
```

**Comment by karenzone** [comment]
@jsvd  Awesome news!  I can easily fix the regressions.  
* Filter is pending publish for a CI issue. I will follow up with the status of yaauie's PR to fix this. 
* Input-log4j will continue to throw errors until we tweak the scripts to only pick up doc diff when the version changes.

**Review by karenzone — CHANGES_REQUESTED** [review]
Contains changes that introduce unwanted regressions. Regressions need to be removed.

**Review by karenzone — APPROVED** [review]
Removed regressions. Builds cleanly and LGTM

**Pull request merged**
