### PR TITLE
Add Agent to list of input plugins

### PR DESCRIPTION
**Pull request by karenzone**
**PREVIEW:** https://logstash-docs_1011.docs-preview.app.elstc.co/guide/en/logstash/master/plugins-inputs-elastic_agent.html

Related: https://github.com/elastic/logstash/issues/12794

Add placeholder file
Add include statement and entry in list of input plugins
Add and verify target pages to avoid broken links

### CODE REVIEW

**Comment by karenzone** [comment]
This PR won't pass elasticsearch-ci/docs until after https://github.com/elastic/logstash-docs/pull/1021 is merged. 

```
13:46:19 INFO:build_docs:Bad cross-document links:
13:46:19 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/logstash/master/plugins-inputs-elastic_agent.html contains broken links to:
13:46:19 INFO:build_docs:   - en/logstash-versioned-plugins/current/input-elastic_agent-index.html
```

**Comment by karenzone** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by karenzone** [comment]
Broken link issue resolved after merge of https://github.com/elastic/docs-tools/pull/54.

**Review by yaauie — APPROVED** [review]
LGTM :+1:

**Pull request merged**
