### PR TITLE
Consolidate plugin list

### PR DESCRIPTION
**Pull request by acchen97**
Consolidating plugin list, to merge at 5.1 launch.

### CODE REVIEW

**Comment by acchen97** [comment]
@dedemorton @suyograo should be a quick review, will merge alongside 5.1 release.

**Comment by dedemorton** [comment]
Looks Groovy To Me (the files build cleanly). Thanks for not making me do this. :-)

**Comment by dedemorton** [comment]
@acchen97 So just to clarify, you want us to wait until 5.1 to merge this, right? And then we should merge it into 5.0, 5.1, 5.x, and master, right?

**Comment by acchen97** [comment]
@dedemorton yep will make sure to do so, thanks for the review.

**Comment by suyograo** [comment]
LGTM

**Comment by jordansissel** [comment]
Wait. Why was this done on Logstash-docs? Shouldn't it be in the Logstash
repo under docs?  Reason being is the next docs sync job will probably
revert this change.

**Comment by dedemorton** [comment]
@jordansissel There are a few files in the plugin docs that are still static and need to be updated in logstash-docs (the overview files for each plugin type). We do plan to automate this eventually, but right now, the single truth of source for this file is in logstash-docs.

**Pull request merged**
