### PR TITLE
Manual build of 7.0 versioned plugin docs

### PR DESCRIPTION
**Pull request by robbavey**

### CODE REVIEW

**Comment by robbavey** [comment]
@jsvd, @karenzone Manual build of 7.0 versioned plugin docs - can you make sure that all the expected plugins are there (and no extra ones)? I had to use an old version of the `Gemfile`, as the latest `Gemfile.template` doesn't include default plugins, which causes the gradle task to generate the json marks most of the plugins as non default.

**Comment by karenzone** [comment]
I verified that everything builds correctly and looks good.  I'm glad to see google_cloud_storage is present.  After this PR is merged, I'll be able to merge #679 *for 7.0 branch*.

**Comment by jsvd** [comment]
@robbavey we added these plugins to the package, can you get their docs in as well?
> logstash-codec-avro
> logstash-filter-prune
> logstash-filter-uuid
> logstash-input-couchdb_changes

**Comment by robbavey** [comment]
@karenzone @jsvd Changes are up

**Comment by karenzone** [comment]
Still builds cleanly and still LGTM

**Pull request merged**
