### PR TITLE
Delineate elastic vs community supported plugins

### PR DESCRIPTION
**Pull request by dedemorton**
Organized plugin overview page to separate elastic supported plugins from community supported one. Also alphabetized the lists

@acchen97 @suyograo 

A few remaining issues:

- What do I do with the docs for these plugins? `logstash-output-null` and `ogstash-filter-checksum`. Should they be removed? If not, are the Elastic or community supported?
- `logstash-filter-de_dot` is in the docs, but not the spreadsheet.
- The following plugins are in the spreadsheet, but not the doc. Do we need to generate/add the doc for these?
`````
logstash-input-dynamodb
logstash-input-fluentd
logstash-input-gemfire
logstash-input-log4j2
logstash-input-neo4j
logstash-input-perfmon
logstash-input-cloudwatch
logstash-input-kinesis
logstash-output-elasticsearch-ec2
logstash-output-gemfire
logstash-output-logentries
logstash-output-neo4j
logstash-output-newrelic
logstash-output-slack
logstash-filter-metricize
logstash-filter-oui
logstash-filter-tld
logstash-filter-unique
logstash-filter-yaml
`````
- This doc is not really doc (contains no useful info) : https://www.elastic.co/guide/en/logstash/5.0/plugins-codecs-msgpack.html

### CODE REVIEW

**Comment by dedemorton** [comment]
@ph Just an FYI that I've made a bunch of changes to these pages.

**Comment by acchen97** [comment]
@dedemorton - first off, a huge THANK YOU for going through this audit. I know its not the most fun of work, but it makes a difference. Responses are below. /cc @suyograo 

- `logstash-output-null` and `logstash-filter-checksum` can be removed from the docs.

- `logstash-filter-de_dot` - let’s support this as it was written by Aaron. I know we brought back dots in field names for ES 5.0, but may still be useful for ES 2.x users. I’ll add this to the spreadsheet.

- Can we please add these plugins below into the docs? The others that aren't in this list now have out of date code, and I've marked them accordingly with "Missing documentation" in the spreadsheet.
 - logstash-input-dynamodb
 - logstash-input-fluentd
 - logstash-input-gemfire
 - logstash-input-log4j2
 - logstash-input-cloudwatch
 - logstash-input-kinesis
 - logstash-output-gemfire
 - logstash-output-newrelic
 - logstash-filter-metricize
 - logstash-filter-oui
 - logstash-filter-tld
 - logstash-filter-unique
 - logstash-filter-yaml

- `logstash-codec-msgpack` - let’s keep this as-is for now, and in supported list

**Comment by dedemorton** [comment]
@suyograo @ph I'm not sure who is turning the crank to update the plugin docs, but please see the list that Alvin provides in his commments. I can update the TOC and overview tables, if one of you can generate and add the asciidoc.

**Comment by suyograo** [comment]
@dedemorton I'll generate docs for these missing plugins.

**Comment by suyograo** [comment]
@acchen97 @dedemorton missing docs are in https://github.com/elastic/logstash-docs/pull/305

Out of the list Alvin provided, these plugins' docs are not generated, and need to be removed from the list for reasons listed:

logstash-input-dynamodb: code not yet merged, need to be removed from the list
logstash-input-fluentd: no code, need to be removed from the list
logstash-input-log4j2: no code, need to be removed from the list
logstash-filter-unique: no code, need to be removed from the list

All other plugins' doc are generated.

**Comment by dedemorton** [comment]
I'm going to merge this and then create a separate PR to add the missing plugins (just easier that way).

**Pull request merged**
