### PR TITLE
Small typo in the sqs output description

### PR DESCRIPTION
**Pull request by ph**
Fixes: https://github.com/elastic/logstash/issues/6485

### CODE REVIEW

**Comment by dedemorton** [comment]
LGTM

**Comment by ph** [comment]
@dedemorton for the merges,  I should merge that in what branches? master, 5.x, 5.1, 5.2 ?

**Comment by dedemorton** [comment]
@ph Yes, that sounds right.

**Comment by dedemorton** [comment]
@ph If you can easily merge it into 5.0 without having conflicts, I'd do that branch, too

**Comment by jordansissel** [comment]
Curious -- why do the PR in this repo? (This repo should be generated from sources only, not PR'd against)?

**Comment by jordansissel** [comment]
Strike my previous comment; I see what file is changed here and now have understanding :)

**Comment by ph** [comment]
@dedemorton all the mentioned branches and backported in 5.0

**Pull request closed without merging**
