### PR TITLE
kafka uses topics not queues

### PR DESCRIPTION
**Pull request by alexcb**

### CODE REVIEW

**Comment by ph** [comment]
Hello @alexcb,
Thank you for the PR, This repository is only used in our doc generation process.

Would you mind doing step 2 of the contributing guide? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps


And reopen this PR on the plugin repository located at https://github.com/logstash-plugins/logstash-input-kafka

**Comment by alexcb** [comment]
I followed the nice "edit this page on github" link from 
http://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html

I thought it was pretty cool if there was a quick way to submit typos -- however it looks like that's broken as it sends the pull request to the wrong repo. If you fix the link I could try it again, but don't want to take the effort to open a different PR elsewhere for a one word typo fix.

**Comment by ph** [comment]
I am really sorry for the inconvenience, 
I'll check with the team concerning the edit link and see how we can fix it on our side.

I'll keep this issue open until then.

**Comment by suyograo** [comment]
@alexcb thanks for your contribution. We will make this easier. Tracking this here: https://github.com/elastic/logstash/issues/2864

**Comment by alexcb** [comment]
@ph @suyograo - I am thoroughly impressed by your timeliness and tracking of your PRs. Thanks for looking into it. 
Cheers,
Alex

**Pull request closed without merging**
