### PR TITLE
Add snmp input to plugin docs

### PR DESCRIPTION
**Pull request by karenzone**
Adding snmp input plugin) to docs.

Do not merge this PR until after the generated plugin docs containing the snmp.asciidoc file have been copied and merged into the relevant repos (master, 6.x, and 6.5).

TO DO:
- [ ] Wait for generated doc that includes `snmp.asciidoc`
- [ ] Pull down generated doc and test it with this PR
- [ ] Verify that plugin has been released/published
- [X] Update snmp input doc to provide missing info and delete placeholders. Colin completed this item with https://github.com/logstash-plugins/logstash-input-snmp/pull/36

### CODE REVIEW

**Comment by karenzone** [comment]
@colinsurprenant   FYI. This PR is queued up and ready to merge after we build/verify plugin docs

**Comment by colinsurprenant** [comment]
LGTM

**Comment by colinsurprenant** [comment]
I edited the PR description to use the markdown task list notation!

**Comment by colinsurprenant** [comment]
woot!

**Pull request closed without merging**
