### PR TITLE
Manual plugin docgen for 6.8.7

### PR DESCRIPTION
**Pull request by karenzone**
Plugin docs manually generated for 6.8.7 release

### CODE REVIEW

**Comment by kares** [comment]
@karenzone generator working for you or still problematic?

**Comment by jsvd** [comment]
Seems to continuously fail on old fixed issues ([failure in memcache ttl setting](https://logstash-ci.elastic.co/blue/organizations/jenkins/elastic%2Bdocs-tools%2Blogstash-plugin-docs/detail/elastic%20docs-tools%20logstash-plugin-docs/82/pipeline#log-2068)).

**Comment by karenzone** [comment]
Yes, as jsvd said, the ci job still fails on 6.8 because of two asciidoc formatting issues in memcached v0.1.1. 

If the CI job continued to run, it would fail on cross-document link check because of changes to the Beats FAQ. The changes aren't in 6.8, so I had to replace the current link with the old link.

**Comment by jsvd** [comment]
I've released 0.1.2 that fixes this broken link, a PR for the bump in the lock file for 6.8 is here: https://github.com/elastic/logstash/pull/11649

**Pull request merged**
