### PR TITLE
Remove jms and hipchat outputs (broken plugins)

### PR DESCRIPTION
**Pull request by jordansissel**
Ideally we could have the docs sync tool do this task, but it doesn't today :)

This removes the jms and hipchat output plugins per https://github.com/elastic/logstash/issues/7993#issuecomment-323802264

```
% perl build_docs.pl --doc ../logstash/docs/index.asciidoc --chunk 1
Building HTML from ../logstash/docs/index.asciidoc
Done
See: /home/jls/projects/docs/html_docs/index.html
```

Docs build seems ok. I checked (with firefox) to see if the jms and hipchat outputs were removed.

### CODE REVIEW

**Comment by dedemorton** [comment]
@jordansissel You'll also need to remove the mention that shows up here:

https://www.elastic.co/guide/en/logstash/current/introduction.html

Incidentally you didn't catch this with the local build because Deb had to change the link format in order to accommodate translated versions of the getting started content that have only a sub-set of the topics. The full build will return an error for missing links.

**Comment by jordansissel** [comment]
Good catch. I'll file a PR to remove that reference in the logstash docs.

**Comment by jordansissel** [comment]
https://github.com/elastic/logstash/pull/8115 removes the reference from the Logstash docs.

**Comment by dedemorton** [comment]
Approved pending merge of https://github.com/elastic/logstash/pull/8115

**Comment by jordansissel** [comment]
Merged; closing.

**Pull request closed without merging**
