### PR TITLE
docs build for 6.2.2

### PR DESCRIPTION
**Pull request by danhermann**

### CODE REVIEW

**Comment by jakelandis** [comment]
LGTM, compared to changes in https://github.com/elastic/logstash/compare/v6.2.1...v6.2.2 and looks good. (netflow codec has already been bumped)

**Comment by dedemorton** [comment]
@jakelandis Shouldn't this have been merged already?

**Comment by danhermann** [comment]
@dedemorton, it looks like I missed this one. If it still looks good, I'll merge it.

**Comment by dedemorton** [comment]
@danhermann Merge it!

**Pull request merged**
